### ISSUE TITLE
Using on 2.78 c get error

### ISSUE THREAD

**Issue by LSDsl** [OGRECave/blender2ogre#1]
Create new project (with cube)
Clcik Export- Ogre 3d- Export and get error
```Traceback (most recent call last):
  File "D:\blender-2.78c-windows64\2.78\scripts\addons\io_ogre\ui\export.py", line 78, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "D:\blender-2.78c-windows64\2.78\scripts\addons\io_ogre\ogre\scene.py", line 150, in dot_scene
    xmlparent = doc._scene_nodes
  File "D:\blender-2.78c-windows64\2.78\scripts\addons\io_ogre\ogre\scene.py", line 456, in dot_scene_node_export
    mesh.dot_mesh(ob, path, overwrite=overwrite)
  File "D:\blender-2.78c-windows64\2.78\scripts\addons\io_ogre\ogre\mesh.py", line 620, in dot_mesh
    util.xml_convert(target_file, has_uvs=dotextures)
  File "D:\blender-2.78c-windows64\2.78\scripts\addons\io_ogre\util.py", line 38, in xml_convert
    version = xml_converter_version()
  File "D:\blender-2.78c-windows64\2.78\scripts\addons\io_ogre\util.py", line 32, in xml_converter_version
    return xml_converter_parameters()[1]
  File "D:\blender-2.78c-windows64\2.78\scripts\addons\io_ogre\util.py", line 18, in xml_converter_parameters
    proc = subprocess.Popen([exe,'-v'],stdout=subprocess.PIPE)
  File "D:\blender-2.78c-windows64\2.78\python\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "D:\blender-2.78c-windows64\2.78\python\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

```

**Comment by paroj** [comment]
it could not find the OgreXmlConverter binary, see https://github.com/OGRECave/blender2ogre/blob/master/io_ogre/config.py#L60

the xml should have been written nevertheless and you can invoke OgreXmlConverter manually to get the mesh file.

**Comment by LSDsl** [comment]
no any xml.
set path to OgreXmlConverter and still have same error

**Comment by paroj** [comment]
try https://github.com/OGRECave/blender2ogre#updating-to-new-versions

**Comment by LSDsl** [comment]
Cannot find this file on Windows

**Comment by paroj** [comment]
https://docs.blender.org/manual/ja/dev/getting_started/installing/configuration/directories.html

**Comment by LSDsl** [comment]
![image](https://cloud.githubusercontent.com/assets/1483011/25119566/68845e70-2423-11e7-819d-48531a7475ad.png)

((

**Comment by paroj** [comment]
where does your OgreXmlConverter come from? it works with Ogre 1.10.

**Comment by LSDsl** [comment]
Ogre Command-line Tools (1.7.2) http://www.ogre3d.org/download/tools

About _ogre_debug.txt - no

**Comment by LSDsl** [comment]
Where to get Ogre 1.10 ?

**Comment by paroj** [comment]
should be compiled when you compile ogre - or see here: http://www.ogre3d.org/download/sdk

**Comment by LSDsl** [comment]
I not complie from source. Try 1.9 - also crash. Could U send pre-built binaries of your version?

**Comment by paroj** [comment]
try https://goo.gl/qIcDgl

**Comment by paroj** [comment]
no response for over 1 month
