### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by vido89** [OGRECave/blender2ogre#139]
I'm using `Blender 2.82` and latest  `blender2ogre.`
Im trying to export my character with animations but Im getting this error `AttributeError: 'NoneType' object has no attribute 'name'`
here is log from blender 

```
$ blender 
Read prefs: /home/slobodan/.config/blender/2.82/config/userpref.blend
[ INFO] Starting io_ogre (0, 8, 3)
WARN (rna.define): /build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/makesrna/intern/rna_define.c:1647 RNA_def_property_ui_text: 'Link with selected armature object rather than importing a skeleton.
Use this for importing skinned meshes that don't have their own skeleton.
Make sure you have the correct skeleton selected or the weight maps may get mixed up.' description from 'IM_USE_SELECTED_SKELETON' '' ends with a '.' !
WARN (rna.define): /build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/makesrna/intern/rna_define.c:1647 RNA_def_property_ui_text: 'Use OgreMeshUpgrader/OgreMeshTool instead of Blender to generate the mesh LODs.
OgreMeshUpgrader/OgreMeshTool does LOD by removing edges, which allows only changing the index buffer and re-use the vertex-buffer (storage efficient).
Blenders decimate does LOD by collapsing vertices, which can result in a visually better LOD, but needs different vertex-buffers pe��!6���S�B����!6���!6��o�����!6���!6��8�
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
Read blend: /home/slobodan/OGRE/Character wip2.blender/character_wip2.blend
[DEBUG] Context.blend_data: /home/slobodan/OGRE/Character wip2.blender/character_wip2.blend
[DEBUG] Context.scene.name: Scene
[DEBUG] Self.filepath: /home/slobodan/OGRE/Character wip2.blender/character_wip2.blend
[DEBUG] Self.last_export_path: None
[DEBUG] Self.filepath: /home/slobodan/OGRE/Character wip2.blender/character_wip2.blend
________________________________________________________________________________ 

[ INFO] Target_path: /home/slobodan/OGRE/Character wip2.blender
[ INFO] Target_file_name: character_wip2.blend
[DEBUG] Target_file_name_no_ext: character_wip2
[ INFO] * Processing Scene: character_wip2, path: /home/slobodan/OGRE/Character wip2.blender
[DEBUG] ABABA metarig
[ INFO] * Processing Materials
[WARNING] No materials, not writting .material script
[ INFO] * Exporting root node: metarig 
[ INFO]   - Vertices: 1706
[ INFO]   - Loop triangles: 3356
[ INFO] * Generating: character.mesh.xml
[ INFO] * Writing shared geometry
[DEBUG] * Mesh has NO custom normals
 + Faces [==================================================>] 100.0%   
[ INFO] - Done at 3.31 seconds
[ INFO] * Writing submeshes
[ INFO] - Done at 3.43 seconds
[DEBUG] Removing temporary object: character.001
[ INFO] - Created character.mesh.xml at 3.61 seconds
[ INFO] - Created character.mesh in total time 3.83 seconds
[ INFO] * Generating: character.skeleton.xml
[ INFO] + NLA track: NlaTrack
[ INFO]   - Action name: Run
[ INFO]   -  Strip name: Run
[ INFO]   - Action name: Side_step
[ INFO]   -  Strip name: Side_step
[ INFO]   - Action name: Turn
[ INFO]   -  Strip name: Turn
[ INFO]   - Action name: Idle_sway
[ INFO]   -  Strip name: Idle_sway
Traceback (most recent call last):
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ui/export.py", line 201, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ogre/scene.py", line 199, in dot_scene
    dot_scene_node_export(root, path = path, doc = doc,
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ogre/scene.py", line 672, in dot_scene_node_export
    dot_scene_node_export( child,
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ogre/scene.py", line 525, in dot_scene_node_export
    skeleton.dot_skeleton(ob, path, overwrite=overwrite)
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ogre/skeleton.py", line 54, in dot_skeleton
    fd.write( bytes(skel.to_xml(),'utf-8') )
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ogre/skeleton.py", line 502, in to_xml
    actions[ action.name ] = [action, strip.action_frame_start, strip.action_frame_end]
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

location: <unknown location>:-1
Saved session recovery to '/tmp/quit.blend'
```

and here is OgreXMLConverter log
[OgreXMLConverter.log](https://github.com/OGRECave/blender2ogre/files/8838345/OgreXMLConverter.log)

Edit: Also it does not export texture
Edit2: Here is .blend file 
[Character_wip2.blenderc5ef.zip](https://github.com/OGRECave/blender2ogre/files/8838583/Character_wip2.blenderc5ef.zip)

**Comment by paroj** [comment]
fixed in master

for material export, you must use PrincipledBSDF
