### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '82 (sub 7)'

### ISSUE THREAD

**Issue by vido89** [OGRECave/blender2ogre#140]
Im using blender 2.82 and latest blender to ogre, here is blender log

```
$ blender 
Read prefs: /home/slobodan/.config/blender/2.82/config/userpref.blend
[ INFO] Starting io_ogre (0, 8, 3)
WARN (rna.define): /build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/makesrna/intern/rna_define.c:1647 RNA_def_property_ui_text: 'Link with selected armature object rather than importing a skeleton.
Use this for importing skinned meshes that don't have their own skeleton.
Make sure you have the correct skeleton selected or the weight maps may get mixed up.' description from 'IM_USE_SELECTED_SKELETON' '' ends with a '.' !
WARN (rna.define): /build/blender-RL3axj/blender-2.82.a+dfsg/source/blender/makesrna/intern/rna_define.c:1647 RNA_def_property_ui_text: 'Use OgreMeshUpgrader/OgreMeshTool instead of Blender to generate the mesh LODs.
OgreMeshUpgrader/OgreMeshTool does LOD by removing edges, which allows only changing the index buffer and re-use the vertex-buffer (storage efficient).
Blenders decimate does LOD by collapsing vertices, which can result in a visually better LOD, but needs different vertex-buffers pe@r���'T���}k�	`�a<��0a`��`xs����s�������`
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
Read blend: /home/slobodan/OGRE/FBX/untitled.blend
[DEBUG] Context.blend_data: /home/slobodan/OGRE/FBX/untitled.blend
[DEBUG] Context.scene.name: Scene
[DEBUG] Self.filepath: /home/slobodan/OGRE/FBX/untitled.blend
[DEBUG] Self.last_export_path: None
[DEBUG] Self.filepath: /home/slobodan/OGRE/FBX/untitled.blend
________________________________________________________________________________ 

[ INFO] Target_path: /home/slobodan/OGRE/FBX
[ INFO] Target_file_name: untitled.blend
[DEBUG] Target_file_name_no_ext: untitled
[ INFO] * Processing Scene: untitled, path: /home/slobodan/OGRE/FBX
[DEBUG] ABABA Light
[DEBUG] ABABA Camera
[DEBUG] ABABA Armature
[DEBUG] ABABA character
[ INFO] * Processing Materials
[ INFO] Write (/home/slobodan/OGRE/FBX/male_char01_tex.png)
[ INFO] * Exporting root node: Light 
Traceback (most recent call last):
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ui/export.py", line 201, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ogre/scene.py", line 199, in dot_scene
    dot_scene_node_export(root, path = path, doc = doc,
  File "/home/slobodan/.config/blender/2.82/scripts/addons/io_ogre/ogre/scene.py", line 634, in dot_scene_node_export
    blender_ver_minor = int(blender_version[1])
ValueError: invalid literal for int() with base 10: '82 (sub 7)'

location: <unknown location>:-1

location: <unknown location>:-1
```

and here is [blend file](https://github.com/OGRECave/blender2ogre/files/8840314/untitled.zip)

**Comment by paroj** [comment]
fixed in master
