### ISSUE TITLE
Parser Errors with importing .mesh

### ISSUE THREAD

**Issue by Mjamfan22** [OGRECave/blender2ogre#151]
Here is the errors it gives when importing a .mesh

[https://i.imgur.com/NESv6Zi.png](url)

**Comment by Mjamfan22** [comment]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_ogre\ui\importer.py", line 184, in execute
    ogre_import.load(os.path.join(target_path, target_file_name))
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_ogre\ogre\ogre_import.py", line 1330, in load
    MaterialParser.xCollectMaterialData(meshData, onlyName, folder)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_ogre\ogre\material_parser.py", line 530, in xCollectMaterialData
    MaterialParser.xParseMaterial(meshMaterials, pathMaterial, folder)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_ogre\ogre\material_parser.py", line 314, in xParseMaterial
    tokens = sl.tokenize(data, materialFile)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\io_ogre\ogre\material_parser.py", line 182, in tokenize
    if isNewline(c):
NameError: name 'isNewline' is not defined

location: <unknown location>:-1

**Comment by Mjamfan22** [comment]
This seemed to work. I still get a material error sadly.

https://i.imgur.com/235rqRK.png

**Comment by sercero** [comment]
Oh, yes.

That is something I found as well when trying to import some meshes.

Will look into it.

**Comment by sercero** [comment]
@Mjamfan22 Can you open a new issue and paste the log?

Thanks!
