### ISSUE TITLE
Error during Ogre Material Layers execution

### ISSUE THREAD

**Issue by bohdankornienko** [OGRECave/blender2ogre#16]
After preparing material in Blender I press Ogre Material Layers and I am getting next error:

In console:

Traceback (most recent call last):
  File "blender-2.75-linux-glibc211-x86_64/2.75/scripts/addons/io_ogre/ui/material.py", line 130, in draw
    node = nodes[ self.INDEX ]
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1

As a popup:
Traceback (most recent call last):
  File "blender-2.75-linux-glibc211-x86_64/2.75/scripts/addons/io_ogre/ui/material.py", line 76, in invoke 
  shader.create_material_passes(mat)
  File "blender-2.75-linux-glibc211-x86_64/2.75/scripts/addons/io_ogre/ui/material.py", line 85, in create_material_passes
  node = tree.nodes.new(type='MATERIAL_EXT')
RUntimeError: Error: Node type MATERIAL_EXT undefined

location: <unknown location>: -1

**Comment by bohdankornienko** [comment]
Blender versions: 2.75, 2.78c

Note: Blender 2.66 works fine.

**Comment by paroj** [comment]
probably this is caused by:
https://wiki.blender.org/index.php/Extensions:2.6/Py/API_Changes#Node_Identifiers
