### ISSUE TITLE
Can't export Damaged Helmet correctly for Ogre-next.

### ISSUE THREAD

**Issue by knn217** [OGRECave/blender2ogre#184]
Hello, I was following the "Blender2ogre" documentation to learn how to create and export my assets from Blender.
I tried to export the DamagedHelmet sample model to learn which material setup was correct, but there was no success.

At first, I tried to export from the DamagedHelmet's original setup:
[https://ibb.co/cbLDWP4](url)
but the mesh has no color when loaded in the app:
[https://ibb.co/TLCZSW4](url)
So I tried a new setup, based on the documentation's description for the metallic workflow:
[https://ibb.co/rcbYjhv](url)
but this time, the exporter ran into an error:
`
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_ogre\ui\export.py", line 210, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_ogre\ogre\scene.py", line 199, in dot_scene
    dot_materialsv2json(materials, path, separate_files=config.get('SEPARATE_MATERIALS'), prefix=prefix)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_ogre\ogre\materialv2json.py", line 36, in dot_materialsv2json
    generator.process_materials()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_ogre\ogre\materialv2json.py", line 80, in process_materials
    self.copy_textures()
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_ogre\ogre\materialv2json.py", line 298, in copy_textures
    util.image_magick(image, src_filename, dst_filename, separate_channel=channel)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_ogre\util.py", line 411, in image_magick
    subprocess.call(cmd)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

Are there any other steps I missed for the metallic workflow? This is the most I could get out of the docs.

**Comment by knn217** [comment]
After some attempts, I finally managed to export something that has texture in Ogre-next. The setup is simply just remove everything but the "BaseColor" image texture like so:
https://ibb.co/3kgGYYS

I don't know if this is a feature but this makes the "BaseColor" image texture combine with the "Base Color" Setting underneath (I thought the "BaseColor" image texture would replace the "Base Color" Setting when plugged in, not combine with it).
Here are 2 examples: 
_When the "Base Color" Setting underneath is set to white: https://ibb.co/xfCmmzx
_When the "Base Color" Setting underneath is set to red: https://ibb.co/hdc7dCG

Also, it made no difference when I switched between "sRGB" and "Non-Color" Color Space for the "BaseColor" image texture, which I thought was odd.

**Comment by paroj** [comment]
json material export is a very recent contribution #178. None of the current maintainers is using ogre-next right now. So I guess you are on your own with this one.

The exporter error looks like imagemagick is being called, despite not being installed.

**Comment by knn217** [comment]
So this was actually a bug? I was hoping that there was something wrong with my setup since the latest attempts actually had some improvements. I'll look into the code and imagemagick then, maybe this is just some minor bug that only appears on Windows (I've run into some of these with Ogre). Thanks for the reply tho!

**Comment by knn217** [comment]
I finally managed to deal with this error. The error was from `subprocess.call(cmd)` in "util.py".
The subprocess expects to run "C:\\Program Files\\ImageMagick\\convert.exe" so I had to:
_Remove the version from ImageMagick's directory name 
_Select "Install legacy utilities" when in ImageMagick's installation config (this solution was found here: https://manuelmeyer.net/2016/06/where-is-imagemagicks-convert-exe/)

The exporter runs without error now, here's the setups and results:
![image](https://github.com/OGRECave/blender2ogre/assets/86541274/22d5a385-843a-4441-8dbc-d94d53b8eb0b)
![image](https://github.com/OGRECave/blender2ogre/assets/86541274/9f33e2e7-e64e-42eb-b2cb-6f928aeb4dc4)

Here's one more with an Image texture plugged into base color:
![image](https://github.com/OGRECave/blender2ogre/assets/86541274/d4d949d1-5549-4ab8-81f0-a72c322c0ec4)
![image](https://github.com/OGRECave/blender2ogre/assets/86541274/3be254db-5d2e-4252-924c-abc94c00612b)

I can kinda see some reflected light on the helmet now so this is an improvement, but the model loaded still doesn't look anything like in Blender, maybe since the lighting in my scene is bad? 

Another thing is that in the 2nd setup, the image texture color is still being combined with the base color underneath (I set it to red). Is this intentional or a bug (since it does look kinda cool)?

**Comment by knn217** [comment]
Hello again, I've created a pull request for some new features that are more fitting for Blender.
