### ISSUE TITLE
Value Error when trying to select the Addon

### ISSUE THREAD

**Issue by loueeee** [OGRECave/blender2ogre#194]
Hello, 

I am completely new to this and I am trying to export an environment (scene?) from Blender to OGRE. I installed it, following the readme and it worked fine. However, now when I want to "select" it by clicking the box I get this error. Does anyone have an idea of how to fix it?
Thank you so much in advance!

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/OGRECave blender2ogre master io_ogre/__init__.py", line 114, in register
    bpy.utils.register_class(clazz)
ValueError: register_class(...): already registered as a subclass 'OGRE_MT_mini_report'

**Comment by sercero** [comment]
Can you post screenshots of what you are doing?

What box did you click?

Thanks

**Comment by sercero** [comment]
"/Applications/Blender.app/Contents/Resources/3.5/scripts/addons/OGRECave blender2ogre master io_ogre/**init**.py", line 114, in register bpy.utils.register_class(clazz) ValueError: register_class(...): already registered as a subclass 'OGRE_MT_mini_report'

What is up with that path?

Is it really installed at "addons/OGRECave blender2ogre master io_ogre/"?

It should be "addons/io_ogre"...

You have to copy the folder "io_ogre" from the downloaded zip to the Blenders "addons" folder.

**Comment by loueeee** [comment]
![Screen Shot 2024-02-09 at 9 52 44 AM](https://github.com/OGRECave/blender2ogre/assets/159402781/990e6e12-439b-4d4d-9be2-bbd12c1a11e3)
![Screen Shot 2024-02-09 at 9 54 07 AM](https://github.com/OGRECave/blender2ogre/assets/159402781/13b484ce-5374-4657-8ac4-ab3f1668bd77)

Thank you for your answer. 

I am not sure why this path shows up. I added the zip in the Blenders "addons" folder. Would it be possible for my computer to look for these files in other folders?

**Comment by sercero** [comment]
> I am not sure why this path shows up. I added the zip in the Blenders "addons" folder. Would it be possible for my computer to look for these files in other folders?

No, that was a mistake.

The proper way to install the plugin is to download the zip in some folder, uncompress it and then copy __only__ the `io_ogre` folder into Blenders add-ons folder

**Comment by loueeee** [comment]
I thought that's what I did, is the io_ogre folder the ogre folder that we can see from my picture?

I am sorry if this is common sense, I am not used to doing this type of thing.

**Comment by loueeee** [comment]
![Screen Shot 2024-02-09 at 10 28 29 AM](https://github.com/OGRECave/blender2ogre/assets/159402781/eaf8490c-a3e7-4694-967e-edc65629951a)

I used this folder zipped to install the add on

**Comment by sercero** [comment]
> I used this folder zipped to install the add on

Oh, you zipped the folder io_ogre folder and then installed it?

I don't know what would that do, the "proper" way would be to unzip what you downloaded from the github repo and then from that zip copy only the "io_ogre" folder into the Blender add-ons folder.

From the screenshot it seems that you only have the contents of "io_ogre" in your addons Blender folder and that seems wrong.

In you Blenders add-on folder you should have other folders with io_something.

I understand that our way of installing the add-on is not the best.

I don't remember now why it was not possible to simply create an installable zip as other plugins do.

**Comment by loueeee** [comment]
I only dowloaded the "io_ogre" folder from the GitHub, I then unzip it and copied that folder to the Blender "addons". 

"From the screenshot it seems that you only have the contents of "io_ogre" in your addons Blender folder and that seems wrong."
Do you mean that there should be an extra folder in the "addons" folder called "io_ogre" with all the contents that I currently have?

"In your Blenders add-on folder you should have other folders with io_something." 
The io_something folders should be the other preinstalled Blender addons?

**Comment by loueeee** [comment]
I found other io_something files but in another path than where they are suppose to be in?
![Uploading Screen Shot 2024-02-09 at 10.52.12 AM.png…]()

**Comment by sercero** [comment]
There might be something different in MacOS, unfortunately I'm not familiar with that Operating System.

The "io_ogre" folder should be with the other "io_{something}" folders.

That should be the "proper" way to install the addon.

I was just recapping how the Blender install addon works and that is incompatible with the way that github packages the repository and that is why we are not doing it that way.

**Comment by loueeee** [comment]
Ok, no worries! Thank you very much for your help. I will keep on trying to understand this and hopefully make it work.

**Comment by loueeee** [comment]
I am now having a different error.
![Screen Shot 2024-02-09 at 11 20 44 AM](https://github.com/OGRECave/blender2ogre/assets/159402781/6a214074-492d-4640-bd28-ac6d957125a1)

**Comment by sercero** [comment]
It seems that you didn't configure the plugin.

When you activate the plugin from the Blenders add-ons options there are some settings to configure like the path to your OGRE binaries

Also, the bug you found is legit (should be "Report.errors")

**Comment by loueeee** [comment]
Ok thanks! 
Do I need to change something here ?
![Screen Shot 2024-02-09 at 11 52 39 AM](https://github.com/OGRECave/blender2ogre/assets/159402781/e341feb8-303f-4ee1-8ce5-8ab76728076b)

**Comment by sercero** [comment]
Are `OgreXMLConverter` and `OgreMeshUpgrader` in those paths?

**Comment by loueeee** [comment]
No, they should be with the other files in addons, right?

**Comment by sercero** [comment]
No, they are from your OGRE installation.

This add-on is to convert Blender files into OGRE .mesh files.

You should have OGRE already installed to use this.

**Comment by loueeee** [comment]
Yes, I have OGRE installed but not those specific files OgreXMLConverter and OgreMeshUpgrader

**Comment by sercero** [comment]
How did you install it (OGRE)?

Without those files (`OgreXMLConverter` being the most important) you won't be able to convert Blender files to OGRE mesh.

Are you sure those files are not present? Perhaps in Mac they have another extension.

**Comment by loueeee** [comment]
I downloaded it from https://www.ogre3d.org/download/sdk/sdk-ogre
and followed the steps. I cannot seem to find those files, unfortunately. 

Sorry this is frustrating, I have just never dealt with anything of this kind.

**Comment by sercero** [comment]
But, which one did you download?

**Comment by loueeee** [comment]
Ok, I joined Gitter now!

**Comment by sercero** [comment]
Oh, you just downloaded the source code?

You have to build it...

**Comment by loueeee** [comment]
Yes :( Building is referring to "installing" it?
I saw that I might need to use Cmake ?

**Comment by sercero** [comment]
It does not seem like it for MacOS

You have to build it and then install it, yes using CMake

**Comment by loueeee** [comment]
Ok, this will then be my next challenge. Thank you for your continuous help!

**Comment by sercero** [comment]
You can use ogre-python to avoid having to compile things and it is more user friendly
