### ISSUE TITLE
Crash exporting on Blender 4.0.2

### ISSUE THREAD

**Issue by sercero** [OGRECave/blender2ogre#209]
#### System Information
- Blender Version: 4.0.2

#### blender2ogre.log
```
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\OGRE\blender-4.0.2-windows-x64\4.0\scripts\addons\io_ogre\ui\export.py", line 219, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "D:\OGRE\blender-4.0.2-windows-x64\4.0\scripts\addons\io_ogre\ogre\scene.py", line 214, in dot_scene
    dot_scene_node_export(root, path = path, doc = doc,
  File "D:\OGRE\blender-4.0.2-windows-x64\4.0\scripts\addons\io_ogre\ogre\scene.py", line 681, in dot_scene_node_export
    a.setAttribute('linear', '%6f' % (1.0 / ob.data.distance))
AttributeError: 'PointLight' object has no attribute 'distance'
Location: D:\OGRE\blender-4.0.2-windows-x64\4.0\scripts\modules\bpy\ops.py:109
```

#### Detailed description
It seems at some point this property was deprecated: `ob.data.distance` for Lights.

The property I see that is common to all Blender 2.8x+ versions is `ob.data.cutoff_distance`

From https://docs.blender.org/api/2.83/bpy.types.Light.html:
- `distance`: Falloff distance - the light is at half the original intensity at this point
- `cutoff_distance`: Distance at which the light influence will be set to 0

@paroj do you think that replacing `distance` with `cutoff_distance` would be a proper fix?

I'm not sure about the light calculations but I think that `cutoff_distance` is actually the proper attribute.

**Comment by sercero** [comment]
Solved by #211
