### ISSUE TITLE
Error: OgreXMLConverter not found

### ISSUE THREAD

**Issue by aniket345** [OGRECave/blender2ogre#21]
![capture](https://user-images.githubusercontent.com/37485204/37559299-922c9d46-2a49-11e8-873b-16381b1ad52d.PNG)

**Comment by Bamarin** [comment]
I get the same error when i try to export (using Linux)

**Comment by Bamarin** [comment]
@paroj that's true for Windows, though it isn't necessary in Linux. I solved by installing `ogre` package. I didn't think it was necessary

**Comment by Legrafc** [comment]
Hello,
I have a problem with the Ogre exporter, you already have it and change the route as you indicate
Please, can you help me, that you sell me an error.

thanks


_### Copy the io_ogre folder into the $BLENDER_DIR/scripts/addons folder. Note on Windows: you have to set the correct path to OGRETOOLS_XML_CONVERTER in io_ogre/config.py prior to the first run.
After installing the addon enable it in Blender from User Preferences > Add-Ons > Import-Export. Search for ogre and check the box on the right. Remember to save as default if you want the addon to be enabled after you exit your Blender.
Integrated help docs will be shown in the upper right hand toolbar, replacing blender's normal Help menu, read them for assistance._

![error blender](https://user-images.githubusercontent.com/38747414/39289652-9ef972a2-48f2-11e8-989c-2979229462d5.jpg)
![error blender1](https://user-images.githubusercontent.com/38747414/39289722-e50721b8-48f2-11e8-9f60-09cd38810210.JPG)

**Comment by D0natell4** [comment]
Hi I found the solution. 
Go to this link: [http://wiki.ogre3d.org/OgreXmlConverter] and dowload the XMLConverter for Windows. in this link you will find the .exe files for OgreXMLConverter and OgreMeshMagick tools. 
Then change the path in config.py in io_ogre folder that you already put in blendes addons folder. As path use the new folder you just download. 
I hope it is clear and will work.

**Comment by frudas24** [comment]
Hi, it works in blender2ogre-0.7 but the master one is not working.
i Put a fake path and get:

`INFO:root:target_path C:\Users\Pao Barrios\Documents\Blender\Ogre_Export_Demo\Export
INFO:root:target_file_name cube_simple_2.scene
INFO:root:target_file_name_no_ext cube_simple_2
Processing Scene: name:cube_simple_2, path: C:\Users\Pao Barrios\Documents\Blender\Ogre_Export_Demo\Export
  Processing Materials
DEBUG:root:WARNING: no materials, not writting .material script
      - Exporting root node: root
      - Generating: Cube.mesh.xml
      - Writing shared geometry
        Done at 0.01 seconds
      - Writing submeshes
        Done at 0.01 seconds
      - Created .mesh.xml at 0.02 seconds
Traceback (most recent call last):
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ui\export.py", line 101, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 159, in dot_scene
    xmlparent = doc._scene_nodes
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 572, in dot_scene_node_export
    xmlparent=o
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 572, in dot_scene_node_export
    xmlparent=o
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 466, in dot_scene_node_export
    mesh.dot_mesh(ob, path, overwrite=overwrite)
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\mesh.py", line 620, in dot_mesh
    util.xml_convert(target_file, has_uvs=dotextures)
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\util.py", line 48, in xml_convert
    version = xml_converter_version()
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\util.py", line 42, in xml_converter_version
    return xml_converter_parameters()[1]
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\util.py", line 28, in xml_converter_parameters
    proc = subprocess.Popen([exe,'-v'],stdout=subprocess.PIPE)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado (translation: the sistem can´t found specific file)


location: <unknown location>:-1

location: <unknown location>:-1`




and put the right one a get other errors:
`INFO:root:target_path C:\Users\Pao Barrios\Documents\Blender\Ogre_Export_Demo\Export
INFO:root:target_file_name cube_simple_2.scene
INFO:root:target_file_name_no_ext cube_simple_2
Processing Scene: name:cube_simple_2, path: C:\Users\Pao Barrios\Documents\Blender\Ogre_Export_Demo\Export
  Processing Materials
DEBUG:root:WARNING: no materials, not writting .material script
      - Exporting root node: root
      - Generating: Cube.mesh.xml
      - Writing shared geometry
        Done at 0.01 seconds
      - Writing submeshes
        Done at 0.01 seconds
      - Created .mesh.xml at 0.02 seconds
Unknown input type.
Traceback (most recent call last):
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ui\export.py", line 101, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 159, in dot_scene
    xmlparent = doc._scene_nodes
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 572, in dot_scene_node_export
    xmlparent=o
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 572, in dot_scene_node_export
    xmlparent=o
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\scene.py", line 466, in dot_scene_node_export
    mesh.dot_mesh(ob, path, overwrite=overwrite)
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\ogre\mesh.py", line 620, in dot_mesh
    util.xml_convert(target_file, has_uvs=dotextures)
  File "C:\Users\Pao Barrios\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_ogre\util.py", line 84, in xml_convert
    assert ret == 0, "OgreXMLConverter failed"
AssertionError: OgreXMLConverter failed

location: <unknown location>:-1

location: <unknown location>:-1`

**Comment by Legrafc** [comment]
HelloCheck this link, 
Blender exporting Sinbad problem - Ogre Forums


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Blender exporting Sinbad problem - Ogre Forums


 |

 |

 |




it helps me a lot to export animated objects, but the objects with animated bones are not good for me, the mesh is deformed, they say that the objects must have few bones, it does not support many.I recommend you and if you serve better export in FBX.I hope it helps you

    El miércoles, 7 de noviembre de 2018 11:28:15 GMT-6, D0natell4 <notifications@github.com> escribió:  
 
 
Hi,
did you find the solution for the Ogre exporter? I'm struggling with the same problem.

Thanks

**Comment by paroj** [comment]
not an error any more
