### ISSUE TITLE
Blender 2.79 - Exporting error with vertex groups

### ISSUE THREAD

**Issue by Webbeh** [OGRECave/blender2ogre#23]
Hello.

While trying to export a really basic animation (rotating cube), I am having this error : 

```KeyError: 'bpy_prop_collection.get(key, ...): key must be a string or tuple, not int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oak/.config/blender/2.79/scripts/addons/io_ogre/ui/export.py", line 101, in execute
    scene.dot_scene(target_path, target_file_name_no_ext)
  File "/home/oak/.config/blender/2.79/scripts/addons/io_ogre/ogre/scene.py", line 156, in dot_scene
    xmlparent = doc._scene_nodes
  File "/home/oak/.config/blender/2.79/scripts/addons/io_ogre/ogre/scene.py", line 463, in dot_scene_node_export
    mesh.dot_mesh(ob, path, overwrite=overwrite)
  File "/home/oak/.config/blender/2.79/scripts/addons/io_ogre/ogre/mesh.py", line 230, in dot_mesh
    append_triangle_in_vertex_group(mesh, ob, vertex_groups, face, tri)
  File "/home/oak/.config/blender/2.79/scripts/addons/io_ogre/ogre/mesh.py", line 657, in append_triangle_in_vertex_group
    group = obj.vertex_groups.get(g.group)
SystemError: <built-in method get of bpy_prop_collection object at 0x7f0a29333510> returned a result with an error set

location: <unknown location>:-1
```

Here's the problematic .blend : 
[problematic.zip](https://github.com/OGRECave/blender2ogre/files/2024420/problematic.zip)

The error started appearing after weight painting (which assigns vertex groups to the mesh).

It is related to error #22

**Comment by Webbeh** [comment]
This same error appears with the Sinbad model too.

**Comment by RobJames-Texas** [comment]
vertex_groups.get expects a string, not an index.
